---
- name: "Bootstrap Ansible Role Files"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_role"
      tags:
        - "tool.bootstrap_role"
      vars:
        bootstrap_role__user: "{{ input_bootstrap_role__user }}"
        bootstrap_role__base_path: "{{ input_bootstrap_role__base_path }}"
        bootstrap_role__meta_author: "{{ input_bootstrap_role__meta_author }}"
        bootstrap_role__meta_namespace: "{{ input_bootstrap_role__meta_namespace }}"
        bootstrap_role__meta_role_name: "{{ input_bootstrap_role__meta_role_name }}"
        bootstrap_role__meta_description: "{{ input_bootstrap_role__meta_description }}"
        bootstrap_role__meta_company: "{{ input_bootstrap_role__meta_company }}"
        bootstrap_role__meta_license: "{{ input_bootstrap_role__meta_license }}"
        bootstrap_role__tags: "{{ input_bootstrap_role__tags }}"
        bootstrap_role__molecule_driver: "{{ input_bootstrap_role__molecule_driver }}"
        bootstrap_role__path: "{{ input_bootstrap_role__path }}"
        bootstrap_role__folders: "{{ input_bootstrap_role__folders }}"
        bootstrap_role__molecule_scenarios: "{{ input_bootstrap_role__molecule_scenarios }}"
        bootstrap_role__inventory_groups: "{{ input_bootstrap_role__inventory_groups }}"
        bootstrap_role__requirements: "{{ input_bootstrap_role__requirements }}"
        bootstrap_role__platforms: "{{ input_bootstrap_role__platforms }}"
        bootstrap_role__molecule_test_sequence: "{{ input_bootstrap_role__molecule_test_sequence }}"
        bootstrap_role__configuration_files: "{{ input_bootstrap_role__configuration_files }}"
        bootstrap_role__ssl: "{{ input_inv_bootstrap_role__ssl }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_role"
