---
- name: "Bootstrap Ansible Role Files"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_user: root

  tasks:

    - name: "Include tool.bootstrap_playbook"
      tags:
        - "tool.bootstrap_playbook"
      vars:
        bootstrap_playbook__user: "{{ input_bootstrap_playbook__user }}"
        bootstrap_playbook__base_path: "{{ input_bootstrap_playbook__base_path }}"
        bootstrap_playbook__meta_author: "{{ input_bootstrap_playbook__meta_author }}"
        bootstrap_playbook__meta_namespace: "{{ input_bootstrap_playbook__meta_namespace }}"
        bootstrap_playbook__meta_role_name: "{{ input_bootstrap_playbook__meta_role_name }}"
        bootstrap_playbook__meta_description: "{{ input_bootstrap_playbook__meta_description }}"
        bootstrap_playbook__meta_company: "{{ input_bootstrap_playbook__meta_company }}"
        bootstrap_playbook__meta_license: "{{ input_bootstrap_playbook__meta_license }}"
        bootstrap_playbook__tags: "{{ input_bootstrap_playbook__tags }}"
        bootstrap_playbook__molecule_driver: "{{ input_bootstrap_playbook__molecule_driver }}"
        bootstrap_playbook__path: "{{ input_bootstrap_playbook__path }}"
        bootstrap_playbook__folders: "{{ input_bootstrap_playbook__folders }}"
        bootstrap_playbook__molecule_scenarios: "{{ input_bootstrap_playbook__molecule_scenarios }}"
        bootstrap_playbook__inventory_groups: "{{ input_bootstrap_playbook__inventory_groups }}"
        bootstrap_playbook__requirements: "{{ input_bootstrap_playbook__requirements }}"
        bootstrap_playbook__platforms: "{{ input_bootstrap_playbook__platforms }}"
        bootstrap_playbook__molecule_test_sequence: "{{ input_bootstrap_playbook__molecule_test_sequence }}"
        bootstrap_playbook__configuration_files: "{{ input_bootstrap_playbook__configuration_files }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_playbook"
